name: Upload to Test PyPI

on:
  push:
    branches:
      - release/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      POETRY_HOME: /opt/poetry
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install poetry
        run: |
          wget https://raw.githubusercontent.com/python-poetry/install.python-poetry.org/d62875fc05fb20062175cd14d19a96dbefa48640/install-poetry.py
          python install-poetry.py --version 1.2.0
      - name: Install dependencies
        run: |
          $POETRY_HOME/bin/poetry install
      - name: Configure poetry for Test PyPI repository
        run: |
          $POETRY_HOME/bin/poetry config repositories.test-pypi https://test.pypi.org/legacy/
          $POETRY_HOME/bin/poetry config pypi-token.test-pypi ${{ secrets.TEST_PYPI_TOKEN }}
      - name: Build and publish package
        run: |
          $POETRY_HOME/bin/poetry publish --build -r test-pypi